import { BookingStatus } from './booking'
import { UserRole } from './user'

export const ErrorCodes = {
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_ROLE_DENIED_STUDENT: `AUTH_ROLE_DENIED_${UserRole.STUDENT}`,
  AUTH_ROLE_DENIED_COACH: `AUTH_ROLE_DENIED_${UserRole.COACH}`,
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  BOOKING_STATUS_PENDING_LOCKED: `BOOKING_STATUS_${BookingStatus.PENDING}_LOCKED`,
  BOOKING_STATUS_CONFIRMED_LOCKED: `BOOKING_STATUS_${BookingStatus.CONFIRMED}_LOCKED`,
  BOOKING_STATUS_COMPLETED_LOCKED: `BOOKING_STATUS_${BookingStatus.COMPLETED}_LOCKED`,
  BOOKING_STATUS_CANCELLED_LOCKED: `BOOKING_STATUS_${BookingStatus.CANCELLED}_LOCKED`,
  BOOKING_TRANSITION_INVALID: 'BOOKING_TRANSITION_INVALID',
  BODY_METRIC_INVALID: 'BODY_METRIC_INVALID',
  RATE_LIMITED: 'RATE_LIMITED'
} as const

